#!/usr/bin/env python3
"""
Create Gmail **drafts** for Hit List rows with Status = **Bulk Info Requested** and Email set,
with the wholesale / retail-pack **PDF** attached.

Parallel to ``suggest_manager_followup_drafts.py`` but:
- Different Hit List status and subject/body template (pricing sheet focus).
- **Does not** use Grok (--use-grok is not offered).
- **Does not** change manager-follow-up behavior (separate script).

Same cadence rules as manager follow-up: pending_review + open draft blocks; min days since
last **Email Agent Follow Up** row per ``to_email``. Run ``sync_email_agent_followup.py`` first
so the log includes sends for **Bulk Info Requested** rows (sync script includes that status).

Usage:
  cd market_research
  python3 retail_price_list/generate_retailer_wholesale_attachment_pdf.py   # refresh PDF if needed
  python3 scripts/sync_email_agent_followup.py
  python3 scripts/suggest_bulk_info_drafts.py --dry-run
  python3 scripts/suggest_bulk_info_drafts.py --max-drafts 5
"""

from __future__ import annotations

import argparse
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
_SCRIPTS = _REPO / "scripts"
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

import suggest_manager_followup_drafts as sm

BULK_STATUS = "Bulk Info Requested"
BULK_PROTOCOL_VERSION = "BULK_INFO_PDF v0.1"
DEFAULT_PDF = _REPO / "retail_price_list" / "agroverse_wholesale_retail_overview_2026.pdf"
DEFAULT_ATTACH_FILENAME = "Agroverse_wholesale_retail_overview_2026.pdf"


def draft_subject_bulk(shop_name: str) -> str:
    s = (shop_name or "Following up").strip()
    return f"{s} — Agroverse wholesale overview (PDF attached)"


def draft_body_bulk(shop_name: str, snippets: list[str]) -> str:
    shop = shop_name or "there"
    lines = [
        "Hi —",
        "",
        f"Following up on the wholesale / bulk pricing overview for {shop}. "
        "I've attached a brief two-page PDF: pricing and retail-pack terms on page 1, "
        "farm taste profiles on page 2 (including cacao tea bulk pricing and traceability links).",
        "",
        "I'm happy to answer questions by email or on a quick call — no need for another in-person stop on my side.",
        "",
    ]
    if snippets:
        lines.append("(Recent email thread — edit freely:)")
        for s in snippets:
            lines.append(f"— {s[:400]}{'…' if len(s) > 400 else ''}")
        lines.append("")
    lines.extend(
        [
            "Thanks,",
            "Gary",
            "Agroverse | ceremonial cacao for retail",
            "garyjob@agroverse.shop",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=f"Create Gmail drafts with wholesale PDF for Hit List status {BULK_STATUS!r}."
    )
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--max-drafts",
        type=int,
        default=0,
        help="Cap new drafts per run; 0 = no limit.",
    )
    parser.add_argument(
        "--min-days-since-sent",
        type=float,
        default=sm.DEFAULT_MIN_DAYS_SINCE_SENT,
        help=f"Min days since last logged send in {sm.LOG_WS!r} (default {sm.DEFAULT_MIN_DAYS_SINCE_SENT}).",
    )
    parser.add_argument("--skip-label", action="store_true")
    parser.add_argument("--expected-mailbox", default=sm.EXPECTED_MAILBOX)
    parser.add_argument("--verbose", action="store_true")
    parser.add_argument(
        "--pdf-path",
        type=Path,
        default=DEFAULT_PDF,
        help="Path to PDF attachment (default: retail overview generated by generate_retailer_wholesale_attachment_pdf.py).",
    )
    parser.add_argument(
        "--attachment-filename",
        default=DEFAULT_ATTACH_FILENAME,
        help="Filename shown to recipient.",
    )
    args = parser.parse_args()

    if args.max_drafts < 0:
        sys.stderr.write("--max-drafts must be >= 0.\n")
        sys.exit(2)

    pdf_path = Path(args.pdf_path).resolve()
    if not pdf_path.is_file():
        sys.stderr.write(f"PDF not found: {pdf_path}\n")
        sys.exit(1)

    gcreds = sm.get_gmail_creds()
    gsvc = sm.build("gmail", "v1", credentials=gcreds, cache_discovery=False)
    me = sm.gmail_profile_email(gsvc)
    exp = args.expected_mailbox.strip().lower()
    if me != exp:
        sys.stderr.write(
            f"Gmail profile is {me!r}, expected {exp!r}. Sign in with the correct account or pass --expected-mailbox.\n"
        )
        sys.exit(1)

    sa = sm.get_sheets_client()
    sh = sa.open_by_key(sm.SPREADSHEET_ID)
    hit_ws = sh.worksheet(sm.HIT_LIST_WS)
    sugg_ws = sm.ensure_suggestions_worksheet(sh)
    log_ws = sm.open_follow_up_worksheet(sh)
    log_tab_present = log_ws is not None
    if not log_tab_present:
        print(
            f"WARNING: worksheet {sm.LOG_WS!r} not found — no sent history in sheet; "
            "every recipient is treated as having no logged send (cadence still enforces pending_review only)."
        )

    last_sent = sm.last_sent_utctime_per_to_email(log_ws)
    pending_to, n_reconciled = sm.pending_review_emails_after_gmail_reconcile(
        gsvc, sugg_ws, dry_run=args.dry_run, verbose=args.verbose
    )
    if n_reconciled:
        print(
            f"Reconciled {n_reconciled} row(s) in {sm.SUGGESTIONS_WS!r}: "
            "pending_review → discarded (Gmail draft was deleted or missing)."
        )
    now = datetime.now(timezone.utc)

    targets = sm.load_hit_list_targets(hit_ws, hit_status=BULK_STATUS)
    if not targets:
        print(f"No Hit List rows match {BULK_STATUS!r} with Email.")
        print(
            "EMAIL_AGENT_BULK_DRAFT_RESULT count=0 mode="
            + ("dry_run" if args.dry_run else "live")
            + " reason=no_bulk_info_targets"
            + f" reconciled_stale_rows={n_reconciled}"
        )
        return

    by_email: dict[str, list[dict]] = {}
    for t in targets:
        by_email.setdefault(t["to_email"], []).append(t)

    candidates: list[str] = []
    skipped_pending = 0
    skipped_cadence = 0
    for em in sorted(by_email.keys()):
        if em in pending_to:
            skipped_pending += 1
            if args.verbose:
                print(
                    f"  skip {em}: active pending_review in {sm.SUGGESTIONS_WS!r} "
                    f"(Gmail draft still exists for this address)"
                )
            continue
        prev = last_sent.get(em)
        if prev is not None:
            d = sm.days_since_utc(prev, now)
            if d < args.min_days_since_sent:
                skipped_cadence += 1
                if args.verbose:
                    print(
                        f"  skip {em}: last logged send {d:.1f}d ago "
                        f"(need >= {args.min_days_since_sent}d; sent_at={prev.date().isoformat()})"
                    )
                continue
        candidates.append(em)

    def sort_key(email: str) -> tuple:
        dt = last_sent.get(email)
        if dt is None:
            return (0, email)
        return (1, dt.timestamp(), email)

    candidates.sort(key=sort_key)

    print(f"Mailbox: {me}")
    print(f"Cadence: min {args.min_days_since_sent} days since last row in {sm.LOG_WS!r} for same to_email.")
    print(f"{BULK_STATUS} rows: {len(targets)} | distinct recipients: {len(by_email)}")
    print(f"Logged last-sent recipients: {len(last_sent)} | pending draft recipients: {len(pending_to)}")
    print(f"Skipped: {skipped_pending} (pending draft) | {skipped_cadence} (too soon since last send)")
    cap_note = "no cap (all eligible)" if args.max_drafts == 0 else f"cap={args.max_drafts}"
    print(f"Eligible: {len(candidates)} | will create PDF drafts ({cap_note})")

    if not candidates:
        print(
            "EMAIL_AGENT_BULK_DRAFT_RESULT count=0 mode="
            + ("dry_run" if args.dry_run else "live")
            + " reason=no_eligible_recipients"
            + f" follow_up_tab_present={str(log_tab_present).lower()}"
            + f" distinct_recipients={len(by_email)}"
            + f" skipped_pending_review={skipped_pending}"
            + f" skipped_cadence_too_soon={skipped_cadence}"
            + f" min_days_since_sent={args.min_days_since_sent}"
            + f" reconciled_stale_rows={n_reconciled}"
        )
        return

    label_id: str | None = None
    if not args.dry_run and not args.skip_label:
        label_id = sm.ensure_user_label_id(gsvc, sm.DEFAULT_GMAIL_LABEL)

    created_rows: list[list[str]] = []
    n_made = 0
    synced_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    for to_addr in candidates:
        if args.max_drafts > 0 and n_made >= args.max_drafts:
            break
        sk, shop, rows_str, _hit_notes, _city_st = sm.pick_primary_store(targets, to_addr)
        if args.verbose:
            print(f"  context {to_addr}: row(s)={rows_str!r} locale={_city_st!r}")
        prev = last_sent.get(to_addr)
        prev_s = prev.strftime("%Y-%m-%d UTC") if prev else "none"

        snippets = sm.latest_thread_snippets(gsvc, to_addr, max_snippets=3)
        subj = draft_subject_bulk(shop)
        body = draft_body_bulk(shop, snippets)

        raw = sm.build_message_raw(
            me,
            to_addr,
            subj,
            body,
            attachment_path=pdf_path,
            attachment_filename=args.attachment_filename,
        )

        if args.dry_run:
            print(f"\n--- dry-run bulk PDF draft #{n_made + 1} → {to_addr} ({shop}) ---")
            print(f"Subject: {subj}")
            print(body[:800] + ("…" if len(body) > 800 else ""))
            n_made += 1
            continue

        draft = gsvc.users().drafts().create(userId="me", body={"message": raw}).execute()
        draft_id = draft.get("id", "") or ""
        msg = draft.get("message") or {}
        msg_id = msg.get("id", "") or ""

        if label_id and msg_id:
            try:
                gsvc.users().messages().modify(
                    userId="me",
                    id=msg_id,
                    body={"addLabelIds": [label_id]},
                ).execute()
            except Exception as e:
                sys.stderr.write(f"Warning: could not apply label to draft message {msg_id}: {e}\n")

        sug_id = str(uuid.uuid4())
        preview = body.replace("\n", " ")[: sm.BODY_PREVIEW_MAX]
        notes = (
            f"Bulk info PDF draft; file={pdf_path.name}; cadence min_days={args.min_days_since_sent}; "
            f"last_logged_send={prev_s}. Edit in Gmail before Send."
        )
        row = [
            sug_id,
            synced_at,
            sk,
            shop,
            to_addr,
            rows_str,
            draft_id,
            subj,
            preview,
            "pending_review",
            sm.DEFAULT_GMAIL_LABEL if not args.skip_label else "",
            BULK_PROTOCOL_VERSION,
            notes,
        ]
        created_rows.append(row)
        n_made += 1
        print(f"Created bulk PDF draft #{n_made} id={draft_id!r} → {to_addr} ({shop})")

    if args.dry_run:
        print(
            "EMAIL_AGENT_BULK_DRAFT_RESULT count="
            + str(n_made)
            + " mode=dry_run (previews only; nothing written to Gmail or Sheets)"
            + f" follow_up_tab_present={str(log_tab_present).lower()}"
            + f" eligible_cap={len(candidates)}"
            + f" max_drafts_cap={'unlimited' if args.max_drafts == 0 else str(args.max_drafts)}"
            + f" skipped_pending_review={skipped_pending}"
            + f" skipped_cadence_too_soon={skipped_cadence}"
            + f" min_days_since_sent={args.min_days_since_sent}"
            + f" reconciled_stale_rows={n_reconciled}"
        )
        return

    if created_rows:
        sugg_ws.append_rows(created_rows, value_input_option="USER_ENTERED")
        print(
            f"Appended {len(created_rows)} row(s) to {sm.SUGGESTIONS_WS!r}. "
            f"Review Drafts in Gmail (label: {sm.DEFAULT_GMAIL_LABEL!r})."
        )

    print(
        "EMAIL_AGENT_BULK_DRAFT_RESULT count="
        + str(len(created_rows))
        + " mode=live gmail_drafts_created="
        + str(len(created_rows))
        + " sheet_rows_appended="
        + str(len(created_rows))
        + f" follow_up_tab_present={str(log_tab_present).lower()}"
        + f" eligible_before_cap={len(candidates)}"
        + f" max_drafts_cap={'unlimited' if args.max_drafts == 0 else str(args.max_drafts)}"
        + f" skipped_pending_review={skipped_pending}"
        + f" skipped_cadence_too_soon={skipped_cadence}"
        + f" min_days_since_sent={args.min_days_since_sent}"
        + f" reconciled_stale_rows={n_reconciled}"
    )


if __name__ == "__main__":
    main()
