#!/usr/bin/env python3
"""Regenerate events/index.json — the unified Agroverse event registry.

Two tiers, one file (read this first to understand the whole portfolio):

  - "upcoming": operational events, source of truth = each
    events/<slug>/event.json (planning checklists, QR mint status, host
    check-ins). Edit those files, not the index.

  - "past": published "cacao circle" pages, generated by agroverse_shop's
    scripts/build_events_json.py into
    agroverse_shop/event-details-registration/events.json. We embed that here
    if we can find it (local sibling checkout first, then the published raw
    URL); otherwise the past tier is empty and source_ref is null.

    python3 build_index.py        # run from anywhere; paths are self-relative

Convention doc: agentic_ai_context/EVENTS.md
"""
import datetime
import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

PAST_LOCAL_CANDIDATES = [
    os.environ.get("AGROVERSE_EVENTS_JSON"),
    os.path.join(HERE, "..", "..", "agroverse_shop", "event-details-registration", "events.json"),
    os.path.expanduser("~/Applications/agroverse_shop/event-details-registration/events.json"),
]
PAST_URL = ("https://raw.githubusercontent.com/TrueSightDAO/agroverse_shop_prod/"
            "main/event-details-registration/events.json")


def load_upcoming():
    events = []
    for path in sorted(glob.glob(os.path.join(HERE, "*", "event.json"))):
        with open(path, encoding="utf-8") as f:
            ev = json.load(f)
        ev["path"] = os.path.basename(os.path.dirname(path))
        events.append(ev)
    events.sort(key=lambda e: e.get("date") or "9999-12-31")
    return events


def load_past():
    """Return (events_list, review_list, source_ref)."""
    for cand in PAST_LOCAL_CANDIDATES:
        if cand and os.path.exists(cand):
            with open(cand, encoding="utf-8") as f:
                data = json.load(f)
            return data.get("events", []), data.get("date_review_needed", []), f"local:{cand}"
    try:
        import urllib.request
        with urllib.request.urlopen(PAST_URL, timeout=10) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        return data.get("events", []), data.get("date_review_needed", []), PAST_URL
    except Exception:
        return [], [], None


def main():
    upcoming = load_upcoming()
    past, past_review, past_ref = load_past()

    index = {
        "schema_version": 2,
        "description": (
            "Unified Agroverse event registry. 'upcoming' = operational events "
            "(source: each go_to_market/events/<slug>/event.json). 'past' = published "
            "cacao-circle pages (source: agroverse_shop/event-details-registration, "
            "generated by its build_events_json.py). Regenerate with build_index.py. "
            "Convention: agentic_ai_context/EVENTS.md"
        ),
        "generated_at": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "generated_by": "build_index.py",
        "upcoming": {
            "source": "go_to_market/events",
            "count": len(upcoming),
            "events": upcoming,
        },
        "past": {
            "source": "agroverse_shop/event-details-registration",
            "source_ref": past_ref,
            "count": len(past),
            "date_review_needed": past_review,
            "events": past,
        },
    }

    out = os.path.join(HERE, "index.json")
    with open(out, "w", encoding="utf-8") as f:
        json.dump(index, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"wrote {out} — upcoming: {len(upcoming)}, past: {len(past)} "
          f"(past source: {past_ref or 'UNAVAILABLE'})")


if __name__ == "__main__":
    main()
